import React, { useState, useEffect } from 'react';
import { Quiz, QuizGameItem } from '../../types';

export const SentenceGame = ({ quiz, onComplete, onFail }: { quiz: Quiz, onComplete: () => void, onFail?: () => void }) => {
  const [availableWords, setAvailableWords] = useState<QuizGameItem[]>([]);
  const [placedWords, setPlacedWords] = useState<(QuizGameItem | null)[]>([]);
  useEffect(() => { if (quiz.gameItems) { const shuffled = [...quiz.gameItems].sort(() => Math.random() - 0.5); setAvailableWords(shuffled); setPlacedWords(new Array(quiz.gameItems.length).fill(null)); } }, [quiz]);
  const handlePlaceWord = (word: QuizGameItem) => { const firstEmptyIndex = placedWords.findIndex(w => w === null); if (firstEmptyIndex !== -1) { const newPlaced = [...placedWords]; newPlaced[firstEmptyIndex] = word; setPlacedWords(newPlaced); setAvailableWords(prev => prev.filter(w => w.id !== word.id)); } };
  const handleRemoveWord = (word: QuizGameItem, index: number) => { const newPlaced = [...placedWords]; newPlaced[index] = null; setPlacedWords(newPlaced); setAvailableWords(prev => [...prev, word]); };
  const checkAnswer = () => { const currentSentence = placedWords.map(w => w?.text).join(' '); const correctSentence = quiz.gameItems?.map(w => w.text).join(' '); if (currentSentence === correctSentence) { onComplete(); } else { alert("Mmm... algo no suena bien. ¡Inténtalo de nuevo!"); if (quiz.gameItems) { setAvailableWords([...quiz.gameItems].sort(() => Math.random() - 0.5)); setPlacedWords(new Array(quiz.gameItems.length).fill(null)); } } };
  return (<div className="space-y-6"> <div className="flex flex-wrap gap-2 min-h-[60px] p-4 bg-slate-100 rounded-2xl border-2 border-slate-200 justify-center items-center"> {placedWords.map((word, idx) => (<button key={idx} onClick={() => word && handleRemoveWord(word, idx)} className={`h-12 min-w-[60px] px-3 rounded-xl font-bold text-sm shadow-sm transition-all border-b-4 flex items-center justify-center ${word ? 'bg-white border-slate-300 text-slate-700 animate-pop' : 'bg-slate-200/50 border-slate-300/50 border-dashed'} `} > {word?.text} </button>))} </div> <div className="flex flex-wrap gap-3 justify-center"> {availableWords.map(word => (<button key={word.id} onClick={() => handlePlaceWord(word)} className="bg-sky-500 text-white px-4 py-3 rounded-xl font-black border-b-4 border-sky-700 active:translate-y-1 active:border-b-0 transition-all shadow-lg shadow-sky-200" > {word.text} </button>))} </div> <div className="pt-4"> <button onClick={checkAnswer} disabled={placedWords.some(w => w === null)} className="w-full bg-emerald-500 text-white font-black py-4 rounded-2xl border-b-[6px] border-emerald-700 active:translate-y-1 active:border-b-0 transition-all disabled:opacity-50 disabled:cursor-not-allowed" > ¡Comprobar Frase! </button> </div> </div>);
};